export interface QuestionCategory {
  id: string;
  name: string;
  questions: string[];
}

// Modo Perguntas: todos respondem a MESMA pergunta, menos o impostor, que recebe
// OUTRA pergunta da MESMA categoria. Regra de ouro do design: dentro de uma
// categoria, TODA pergunta deve pedir o mesmo TIPO de resposta (uma pessoa, uma
// comida, um lugar, um filme...). Assim a resposta do impostor combina no formato,
// mas destoa no conteúdo — dá pra pegar, mas não é óbvio. Poucas categorias, cada
// uma bem recheada e coesa.
export const QUESTION_CATEGORIES: QuestionCategory[] = [
  {
    // Resposta = uma PESSOA (alguém do grupo ou famoso). O carro-chefe do humor.
    id: 'galera',
    name: '🎭 Sobre a Galera',
    questions: [
      'Quem é mais provável de ficar milionário?',
      'Quem é mais provável de ir preso?',
      'Quem comeria um inseto por R$50?',
      'Quem some na hora de pagar a conta?',
      'Quem seria o pior pra dividir apartamento?',
      'Quem dá o pior conselho amoroso?',
      'Quem choraria vendo um filme infantil?',
      'Quem largaria tudo pra virar mochileiro?',
      'Quem esconderia um corpo por você sem perguntar nada?',
      'Quem vai se casar primeiro?',
      'Quem checa o celular a cada 5 minutos?',
      'Quem seria péssimo num apocalipse zumbi?',
      'Quem já stalkeou um crush essa semana?',
      'Quem é o mais fofoqueiro do grupo?',
      'Quem gastaria o salário todo em um dia?',
      'Quem é mais provável de dormir numa festa?',
      'Quem levaria a culpa por algo que não fez?',
      'Quem tem mais chance de ficar famoso?',
      'Quem cairia num golpe do Pix?',
      'Quem tem o pior gosto pra música?',
      'Quem chega atrasado em tudo?',
      'Quem seria o pior motorista de aplicativo?',
      'Quem manda áudio de 5 minutos?',
      'Quem contaria seu segredo sem querer?',
      'Quem sobreviveria mais tempo sem o celular?',
      'Quem faria a melhor festa?',
      'Quem é mais provável de brigar por comida?',
      'Quem daria um péssimo professor?',
      'Quem ri na hora errada?',
      'Quem seria o primeiro eliminado num reality?',
      'Quem paga um mico e nem percebe?',
      'Quem seria um ótimo vilão de novela?',
      'Quem é mais provável de adotar 10 gatos?',
      'Quem some do grupo por semanas?',
      'Quem toparia um desafio idiota na hora?',
      'Quem é o mais dramático?',
      'Quem ganharia um concurso de dança?',
      'Quem esquece o aniversário de todo mundo?',
      'Quem mentiria melhor num interrogatório?',
      'Quem seria expulso de um cassino?',
      'Quem é mais provável de virar influencer?',
      'Quem chora de rir por qualquer coisa?',
      'Quem seria o pior parceiro de crime?',
      'Quem toparia morar em outro país amanhã?',
      'Quem tem as piores ideias às 3 da manhã?',
      'Quem seria o último a saber de uma fofoca?',
      'Quem é mais provável de perder o voo?',
      'Quem faria de tudo por comida grátis?',
      'Quem seria o melhor guarda-costas?',
      'Quem cai em toda pegadinha?',
      'Quem é mais provável de dar um perdido no date?',
      'Quem é o mais competitivo num jogo de tabuleiro?',
      'Quem perderia numa queda de braço?',
      'Quem tem o pior histórico de navegador?',
      'Quem é o pior pra guardar um presente surpresa?',
      'Quem é mais provável de começar uma treta na internet?',
      'Quem sairia correndo de um fantasma?',
      'Quem seria o melhor cozinheiro do grupo?',
      'Quem é mais provável de virar um chefe mandão?',
      'Quem gasta demais em besteira?',
      'Quem seria o pior num karaokê?',
      'Quem ganharia na loteria e perderia o bilhete?',
      'Quem toparia raspar a cabeça por uma aposta?',
      'Quem é o mais preguiçoso pra responder mensagem?',
      'Quem seria o melhor pra planejar uma viagem?',
      'Quem é mais provável de dormir no trabalho?',
      'Quem faria a pior tatuagem por impulso?',
      'Quem seria o primeiro a fugir numa briga?',
      'Quem é o mais teimoso do grupo?',
      'Quem contaria uma mentira e esqueceria?',
      'Quem seria o melhor num programa de calouros?',
      'Quem provavelmente já se apaixonou por alguém errado?',
      'Quem seria o pior anfitrião de uma festa?',
      'Quem entraria em pânico numa emergência?',
      'Quem seria o mais fácil de convencer a fazer besteira?',
    ],
  },
  {
    // Resposta = uma COMIDA ou BEBIDA qualquer (sem afunilar pra "fruta", "sobremesa" etc).
    id: 'comida',
    name: '🍕 Comida e Bebida',
    questions: [
      'Qual comida você mais ama?',
      'Qual comida você mais odeia?',
      'Qual comida você comeria pra sempre?',
      'Qual comida é a mais superestimada?',
      'Qual comida você acha nojenta?',
      'Qual comida salva qualquer dia ruim?',
      'Qual comida você defende com a vida?',
      'Qual comida parece ruim mas é ótima?',
      'Qual comida você pediria na última refeição?',
      'Qual comida te lembra a infância?',
      'Qual a melhor comida de madrugada?',
      'Qual comida você enjoa rápido?',
      'Qual comida não pode faltar numa festa?',
      'Qual comida você odeia mas todo mundo ama?',
      'Qual a melhor comida de rua?',
      'Qual comida você comeria mesmo passada da validade?',
      'Qual comida é cara demais pelo que entrega?',
      'Qual comida melhora qualquer ressaca?',
      'Qual comida você nunca provaria?',
      'Qual a melhor comida pra dividir?',
      'Qual comida você esconde pra não dividir?',
      'Qual comida estraga uma refeição inteira?',
      'Qual comida estrangeira você ama?',
      'Qual comida brasileira é imbatível?',
      'Qual comida você faz melhor que a média?',
      'Qual comida você comeria no café, no almoço e na janta?',
      'Qual comida é boa demais pra ser saudável?',
      'Qual comida você comeria de graça pra sempre?',
      'Qual comida causa mais discussão?',
      'Qual comida sua avó fazia perfeita?',
      'Qual comida você levaria pra uma ilha deserta?',
      'Qual bebida não pode faltar num rolê?',
      'Qual bebida você acha horrível?',
      'Qual comida você comeu demais e enjoou pra vida?',
      'Qual comida é melhor requentada?',
      'Qual comida você julga quem não gosta?',
      'Qual comida te deixa feliz na hora?',
      'Qual a pior combinação de comida que existe?',
      'Qual comida você pediria num date?',
      'Qual comida você comeria escondido às 3 da manhã?',
      'Qual comida vale cada caloria?',
      'Qual comida deveria ser proibida?',
      'Qual comida é a mais viciante?',
      'Qual comida você comeria mesmo sem fome?',
      'Qual comida te dá água na boca só de pensar?',
      'Qual a melhor comida pra um dia de preguiça?',
      'Qual comida você acha que é hype à toa?',
      'Qual comida some rápido demais na sua casa?',
      'Qual comida é perfeita pra assistir um filme?',
      'Qual comida você comeria todo fim de semana?',
      'Qual comida representa você?',
      'Qual comida você faria pra impressionar alguém?',
      'Qual comida você pede sempre que sai?',
      'Qual comida você nunca cansaria de comer?',
      'Qual comida você acha que une o Brasil?',
      'Qual comida você comeria mesmo sabendo que faz mal?',
      'Qual comida marca uma boa memória sua?',
      'Qual comida você acha polêmica?',
      'Qual comida você acha melhor fria?',
      'Qual comida você comeria antes de uma prova difícil?',
    ],
  },
  {
    // Resposta = um LUGAR (cidade, país, tipo de lugar).
    id: 'lugares',
    name: '🌍 Lugares',
    questions: [
      'Qual lugar você mais quer conhecer?',
      'Qual lugar você nunca visitaria?',
      'Qual o melhor lugar pra morar?',
      'Qual lugar é o mais superestimado?',
      'Qual lugar você acha mágico?',
      'Qual lugar você acha perigoso demais?',
      'Qual lugar você acha chato?',
      'Qual o melhor lugar pra relaxar?',
      'Qual o lugar mais romântico?',
      'Qual lugar você voltaria agora mesmo?',
      'Pra onde você fugiria por uma semana?',
      'Qual lugar tem a melhor comida?',
      'Qual lugar todo mundo devia conhecer?',
      'Qual lugar você nunca mais voltaria?',
      'Qual a melhor cidade do Brasil?',
      'Qual lugar parece outro planeta?',
      'Qual o melhor lugar pra passar o réveillon?',
      'Qual lugar você acha caro demais?',
      'Pra onde você iria numa viagem com a galera?',
      'Qual lugar você iria sozinho?',
      'Qual lugar tem a melhor vibe?',
      'Qual lugar você acha assustador?',
      'Qual o melhor destino de férias?',
      'Qual lugar você sonha em morar?',
      'Qual cidade tem o melhor clima?',
      'Qual lugar decepciona ao vivo?',
      'Qual o melhor lugar pra uma lua de mel?',
      'Qual lugar você levaria um estrangeiro?',
      'Qual lugar você acha o mais bonito do mundo?',
      'Qual lugar você iria só pela comida?',
      'Pra onde você se mudaria amanhã se pudesse?',
      'Qual lugar tem as melhores festas?',
      'Qual lugar você acha caótico demais?',
      'Qual o melhor lugar pra ver o pôr do sol?',
      'Qual lugar você quer riscar da lista antes de morrer?',
      'Qual cidade você acha subestimada?',
      'Qual lugar você evitaria nas férias?',
      'Qual o melhor lugar pra fazer amigos?',
      'Qual lugar te dá paz?',
      'Qual lugar você acha exagerado pra fotos?',
      'Qual lugar você moraria se dinheiro não importasse?',
      'Qual o pior lugar pra ficar preso?',
      'Qual lugar você acha mais aventureiro?',
      'Qual lugar você conheceria de novo sem pensar?',
      'Qual lugar tem o povo mais simpático?',
      'Qual o melhor lugar pra um feriado prolongado?',
      'Qual lugar você acha que é só hype?',
      'Qual lugar você recomendaria de olhos fechados?',
      'Qual lugar você acha mais surreal?',
      'Qual cidade você acha perfeita pra um date?',
      'Qual lugar você guardaria como segredo?',
      'Qual lugar você acha que mudaria sua vida?',
      'Qual lugar você acha imperdível numa viagem?',
      'Qual lugar te faz sentir em casa?',
    ],
  },
  {
    // Resposta = um FAMOSO ou personagem.
    id: 'famosos',
    name: '⭐ Famosos',
    questions: [
      'Qual famoso é o mais irritante?',
      'Qual famoso você acha o mais talentoso?',
      'Com qual famoso você jantaria?',
      'Qual celebridade é a mais superestimada?',
      'Qual famoso parece ser falso?',
      'Qual famoso daria um bom presidente?',
      'Quem seria seu crush famoso?',
      'Qual famoso você não suporta?',
      'Qual celebridade parece gente boa?',
      'Qual artista você pagaria caro pra ver?',
      'Qual famoso é o mais engraçado?',
      'Qual famoso te decepcionou?',
      'Qual famoso está superexposto?',
      'Qual celebridade envelheceu melhor?',
      'Com qual famoso você trocaria de vida?',
      'Qual famoso merecia mais reconhecimento?',
      'Qual influencer você mais curte?',
      'Qual influencer é insuportável?',
      'Qual famoso você convidaria pra sua festa?',
      'Qual celebridade é uma lenda?',
      'Qual famoso você acha exagerado?',
      'Qual famoso você seguiria pra sempre?',
      'Qual famoso caiu do pedestal pra você?',
      'Qual celebridade você acha misteriosa?',
      'Qual famoso seria um bom amigo?',
      'Qual famoso te surpreendeu pra bem?',
      'Qual celebridade tem o melhor estilo?',
      'Qual famoso você imita?',
      'Qual famoso deveria se aposentar?',
      'Qual famoso brasileiro é imbatível?',
      'Qual famoso você acha genial?',
      'Qual celebridade você acha supervalorizada?',
      'Qual famoso você adoraria conhecer pessoalmente?',
      'Qual famoso parece ser chato na vida real?',
      'Qual famoso você defende sempre?',
      'Qual celebridade tem a melhor história de vida?',
      'Qual famoso você não entende o sucesso?',
      'Qual famoso seria um bom vizinho?',
      'Qual famoso te inspira?',
      'Qual famoso você trollaria se pudesse?',
      'Qual celebridade tem o melhor carisma?',
      'Qual famoso mudaria o mundo se quisesse?',
      'Qual famoso você levaria pra um karaokê?',
      'Qual personagem fictício você queria conhecer?',
      'Qual vilão famoso é o melhor?',
      'Qual herói você queria ser?',
      'Qual personagem representa você?',
      'Qual famoso você acha o mais bonito?',
      'Qual celebridade você acha mais autêntica?',
      'Qual famoso finge ser humilde?',
      'Qual famoso daria o melhor conselho?',
      'Qual famoso você acha que é puro marketing?',
    ],
  },
  {
    // Resposta = um FILME, SÉRIE ou personagem de tela.
    id: 'filmes-series',
    name: '🎬 Filmes e Séries',
    questions: [
      'Qual filme você assiste mil vezes?',
      'Qual filme é o mais superestimado?',
      'Qual série você abandonou no meio?',
      'Qual o melhor filme de todos os tempos?',
      'Qual filme te faz chorar?',
      'Qual série você maratonaria de novo?',
      'Qual final te decepcionou?',
      'Qual filme é ruim mas você ama?',
      'Qual série todo mundo ama menos você?',
      'Qual filme você indicaria pra qualquer um?',
      'Qual o melhor filme de terror?',
      'Qual comédia te faz rir sempre?',
      'Qual série marcou sua vida?',
      'Qual remake não precisava existir?',
      'Qual o melhor filme de animação?',
      'Qual saga é a melhor?',
      'Qual filme você nunca terminou?',
      'Qual série tem o melhor primeiro episódio?',
      'Qual filme é longo demais?',
      'Qual vilão de cinema é o melhor?',
      'Qual personagem você queria ser?',
      'Qual filme te deu medo de dormir?',
      'Qual série você recomendaria pra maratonar?',
      'Qual filme merecia uma continuação?',
      'Qual filme todo mundo elogia e você achou chato?',
      'Qual série tem o pior final?',
      'Qual filme valeu a pena ver no cinema?',
      'Qual personagem te irrita?',
      'Qual filme mudou sua forma de ver algo?',
      'Qual série é a mais viciante?',
      'Qual filme você assistiria com a família?',
      'Qual filme é bom demais pra ver só uma vez?',
      'Qual série você largou e nunca voltou?',
      'Qual filme tem a melhor trilha sonora?',
      'Qual filme você acha subestimado?',
      'Qual série você defende com unhas e dentes?',
      'Qual filme te fez rir sem parar?',
      'Qual filme é perfeito pra um dia de chuva?',
      'Qual reviravolta te pegou de surpresa?',
      'Qual série tem os melhores personagens?',
      'Qual filme você odiou mas todo mundo ama?',
      'Qual filme você reveria agora mesmo?',
      'Qual documentário vale a pena?',
      'Qual filme te fez pensar por dias?',
      'Qual personagem merecia coisa melhor?',
      'Qual série tem a melhor ambientação?',
      'Qual filme é a cara do fim de ano?',
      'Qual filme você indicaria num primeiro date?',
      'Qual série você começaria de novo do zero?',
      'Qual filme envelheceu mal?',
      'Qual filme tem a melhor cena de todas?',
      'Qual série você assistiria de novo sem pensar?',
    ],
  },
  {
    // Resposta = uma MÚSICA, ARTISTA ou banda.
    id: 'musica',
    name: '🎵 Música',
    questions: [
      'Qual a melhor banda de todos os tempos?',
      'Qual música não sai da sua cabeça?',
      'Qual artista é superestimado?',
      'Qual música te faz dançar na hora?',
      'Qual show você sonha em ir?',
      'Qual música pra ouvir quando está triste?',
      'Qual o melhor artista brasileiro?',
      'Qual música todo mundo canta errado?',
      'Qual música é a cara do verão?',
      'Qual artista você ouve escondido?',
      'Qual a melhor música pra um churrasco?',
      'Qual música é um hino?',
      'Qual cantor tem a melhor voz?',
      'Qual música você coloca pra treinar?',
      'Qual música te lembra alguém?',
      'Qual o melhor álbum de todos os tempos?',
      'Qual música gruda na cabeça e não sai?',
      'Qual artista você não entende o sucesso?',
      'Qual música você colocaria no seu casamento?',
      'Qual banda merecia ser mais famosa?',
      'Qual música define a sua vida?',
      'Qual artista você já ouviu demais?',
      'Qual música te dá arrepio?',
      'Qual música é boa pra viajar de carro?',
      'Qual cantor você acha supervalorizado?',
      'Qual música você odiava e passou a amar?',
      'Qual música te faz voltar no tempo?',
      'Qual artista você veria ao vivo de novo?',
      'Qual música anima qualquer festa?',
      'Qual música você canta no chuveiro?',
      'Qual artista você indicaria pra alguém?',
      'Qual música é chiclete demais?',
      'Qual música você coloca pra relaxar?',
      'Qual banda tem o melhor show ao vivo?',
      'Qual música marcou sua adolescência?',
      'Qual gênero musical você não suporta?',
      'Qual música você nunca cansa de ouvir?',
      'Qual artista tem a melhor carreira?',
      'Qual música é perfeita pra um fim de noite?',
      'Qual música você colocaria num filme sobre você?',
      'Qual cantor tem o melhor palco?',
      'Qual música você acha hype à toa?',
      'Qual música te faz chorar?',
      'Qual banda você queria ter visto ao vivo?',
      'Qual música representa o Brasil?',
      'Qual artista é subestimado?',
      'Qual música você ouviria pra sempre?',
      'Qual música bota todo mundo pra cantar junto?',
      'Qual música te dá energia?',
      'Qual artista você acha genial?',
      'Qual música você tocaria pra alguém que ama?',
      'Qual música todo mundo já dançou pelo menos uma vez?',
      'Qual artista você acha que é só marketing?',
    ],
  },
  {
    // Resposta = uma OPINIÃO / coisa (o balde "geral e humor", estilo hot take).
    id: 'hot-takes',
    name: '☝️ Hot Takes',
    questions: [
      'Qual opinião impopular você defende?',
      'Qual coisa é a mais superestimada do mundo?',
      'Qual coisa todo mundo ama e você odeia?',
      'Qual moda foi um erro?',
      'Qual mania da sociedade é ridícula?',
      'Qual coisa cara não vale o preço?',
      'Qual tradição deveria acabar?',
      'Qual coisa "de gente adulta" é um saco?',
      'Qual invenção piorou o mundo?',
      'Qual coisa todo mundo finge que gosta?',
      'Qual regra social não faz sentido?',
      'Qual coisa é hype puro?',
      'Qual hábito das pessoas te irrita?',
      'Qual coisa deveria ser proibida?',
      'Qual coisa você acha exagerada?',
      'Qual tendência você espera que morra logo?',
      'Qual coisa é subestimada e ninguém dá valor?',
      'Qual coisa você defende mesmo sendo polêmica?',
      'Qual coisa moderna é desnecessária?',
      'Qual comportamento na internet é o pior?',
      'Qual coisa te faz revirar os olhos na hora?',
      'Qual coisa "obrigatória" você acha bobagem?',
      'Qual mania de casal é irritante?',
      'Qual coisa virou hype sem motivo?',
      'Qual coisa do passado era melhor?',
      'Qual coisa você mudaria na sociedade?',
      'Qual costume brasileiro é o melhor?',
      'Qual costume brasileiro é o pior?',
      'Qual coisa as pessoas levam a sério demais?',
      'Qual coisa deveria ter um manual de uso?',
      'Qual desculpa esfarrapada todo mundo usa?',
      'Qual coisa é boa na teoria e péssima na prática?',
      'Qual coisa você acha nojenta e ninguém concorda?',
      'Qual coisa é perda de tempo total?',
      'Qual coisa você fingiu gostar pra se enturmar?',
      'Qual coisa te dá vergonha alheia?',
      'Qual coisa é supervalorizada nas redes sociais?',
      'Qual mania de trabalho é a pior?',
      'Qual coisa deveria ser mais barata?',
      'Qual coisa já era pra ter mudado?',
      'Qual coisa as pessoas defendem sem saber por quê?',
      'Qual polêmica é boba demais pra ter virado treta?',
      'Qual coisa é melhor do que dizem?',
      'Qual coisa é pior do que dizem?',
      'Qual atitude é red flag numa amizade?',
      'Qual coisa todo mundo deveria experimentar uma vez?',
      'Qual coisa é cafona mas você ama?',
      'Qual hábito saudável você acha um saco?',
      'Qual coisa antiga não deveria ter saído de moda?',
      'Qual coisa te tira do sério numa fila?',
      'Qual mania de motorista é a pior?',
      'Qual coisa define bom gosto pra você?',
      'Qual coisa cara você acha que virou status à toa?',
      'Qual coisa gratuita que as pessoas não valorizam?',
    ],
  },
  {
    // Resposta = uma AÇÃO / hábito / coisa do dia a dia.
    id: 'vida-social',
    name: '🏠 Vida Diária e Social',
    questions: [
      'Qual a pior parte de uma segunda-feira?',
      'Qual tarefa doméstica você mais empurra com a barriga?',
      'O que você faz assim que acorda?',
      'Qual desculpa você dá pra cancelar um rolê?',
      'Qual a melhor parte de ficar em casa?',
      'O que você faz quando está entediado?',
      'Qual hábito você faz no automático?',
      'Qual a pior parte de acordar cedo?',
      'O que você sempre adia pra depois?',
      'Qual a melhor forma de relaxar depois do trabalho?',
      'O que você faz quando não consegue dormir?',
      'Qual mania você tem no celular?',
      'O que você faz numa fila de espera?',
      'Qual a pior parte de fazer compras?',
      'O que você faz num domingo à tarde?',
      'Qual atividade te dá preguiça só de pensar?',
      'O que você faz quando está sozinho em casa?',
      'Qual parte da rotina você faria de olhos fechados?',
      'O que você sempre esquece de fazer?',
      'Qual a pior parte de dividir casa com alguém?',
      'O que você faz pra passar o tempo no transporte?',
      'Qual tarefa você deixa acumular?',
      'O que você faz quando a internet cai?',
      'Qual a melhor parte de um feriado?',
      'Qual hábito social te cansa?',
      'O que você faz quando chega atrasado?',
      'O que você faz quando não quer falar com ninguém?',
      'Qual parte do dia é a sua favorita?',
      'O que você faz quando o plano da noite dá errado?',
      'Qual atividade em grupo você odeia?',
      'O que você faz pra fugir de uma conversa chata?',
      'Qual desculpa você usa pra sair mais cedo de um rolê?',
      'O que você faz quando esquece o nome de alguém?',
      'Qual a melhor parte de reencontrar amigos?',
      'O que você faz num rolê que você nem queria ir?',
      'Qual a pior parte de organizar um evento?',
      'O que você faz quando alguém está atrasado?',
      'Qual costume seu ninguém entende?',
      'O que você faz assim que chega em casa?',
      'Qual a pior parte da vida adulta?',
    ],
  },
  {
    // Resposta = uma ATITUDE / qualidade / gesto no amor e nos relacionamentos.
    id: 'relacionamentos',
    name: '💘 Relacionamentos',
    questions: [
      'Qual o maior red flag num parceiro?',
      'Qual green flag te ganha na hora?',
      'Qual o pior defeito num relacionamento?',
      'Qual gesto romântico derrete qualquer um?',
      'Qual atitude acaba com o clima na hora?',
      'Qual o pior tipo de ex?',
      'O que faz você perder o interesse?',
      'Qual a maior mancada num primeiro encontro?',
      'Qual qualidade é indispensável num parceiro?',
      'Qual hábito de casal é irritante?',
      'O que é romântico pra você?',
      'Qual o maior sinal de que é amor?',
      'Qual dealbreaker é imperdoável?',
      'O que faz um date ser perfeito?',
      'Qual atitude é carente demais?',
      'Qual a pior desculpa de quem termina com você?',
      'O que te conquista além da aparência?',
      'Qual sinal de que a relação vai dar errado?',
      'Qual gesto pequeno significa muito?',
      'Qual o pior lugar pra um primeiro encontro?',
      'O que te faz confiar em alguém?',
      'Qual comportamento é ciúme demais?',
      'O que é essencial pra uma relação durar?',
      'Qual atitude é falta de respeito na relação?',
      'Qual o maior clichê de relacionamento?',
      'O que faz você se apaixonar?',
      'Qual defeito você perdoaria por amor?',
      'Qual atitude estraga um casamento?',
      'Qual o melhor jeito de reconquistar alguém?',
      'Qual red flag aparece logo no começo?',
      'O que é pedir demais de um parceiro?',
      'Qual sinal de que alguém gosta de você?',
      'Qual atitude você nunca aceitaria?',
      'O que faz o brilho de uma relação sumir?',
      'Qual gesto de carinho é o melhor?',
      'Qual a pior forma de terminar com alguém?',
      'O que faz alguém ser bom de relacionamento?',
      'Qual expectativa irreal as pessoas têm no amor?',
      'Qual atitude reacende a paixão?',
      'Qual o maior teste de um relacionamento?',
    ],
  },
  {
    // Resposta = uma PESSOA (versão picante do "quem é mais provável de..."). 18+.
    id: 'nsfw',
    name: '🔞 NSFW',
    questions: [
      'Quem do grupo já ficou com mais gente?',
      'Quem é mais provável de dar uns pegas num desconhecido na festa?',
      'Quem tem as histórias mais picantes?',
      'Quem já ficou com alguém do grupo?',
      'Quem é o(a) mais safado(a) da turma?',
      'Quem manda a melhor cantada?',
      'Quem é mais provável de ter um crush secreto aqui?',
      'Quem já mandou mensagem arrependida de madrugada?',
      'Quem é mais provável de voltar pro ex?',
      'Quem tem o melhor jogo de conquista?',
      'Quem já ficou com duas pessoas no mesmo dia?',
      'Quem é mais provável de topar um date às cegas?',
      'Quem tem mais matches nos apps?',
      'Quem é o(a) mais ciumento(a)?',
      'Quem some depois de uma noite e não responde mais?',
      'Quem é mais provável de se apaixonar rápido demais?',
      'Quem tem a pior fama de enrolão(a)?',
      'Quem topa mais fácil um rolê duvidoso?',
      'Quem é mais provável de dar em cima de alguém indisponível?',
      'Quem manda mais indireta nas redes?',
      'Quem é mais provável de ter um affair no trabalho?',
      'Quem tem o crush mais improvável?',
      'Quem seria o(a) mais escandaloso(a) num date?',
      'Quem já stalkeou o ex ontem mesmo?',
      'Quem é mais provável de beijar o(a) melhor amigo(a)?',
      'Quem tem mais chance de terminar e voltar na mesma semana?',
      'Quem some do rolê pra ficar com alguém?',
      'Quem já se declarou e levou um fora épico?',
      'Quem tem a queda mais óbvia por alguém aqui?',
      'Quem é mais provável de flertar sem nem perceber?',
      'Quem já trocou de crush no meio da festa?',
      'Quem tem o pior histórico amoroso?',
      'Quem é mais provável de mandar mensagem pro ex bêbado(a)?',
      'Quem seria o(a) primeiro(a) a topar um strip pôquer?',
      'Quem tem mais assunto guardado que ninguém sabe?',
      'Qual o lugar mais inusitado pra ficar com alguém?',
      'Qual parte do corpo mais te atrai em alguém?',
      'O que é sexy sem nenhum esforço?',
      'Qual a maior red flag na cama?',
      'O que estraga o clima na hora H?',
      'Qual fetiche é mais comum do que parece?',
      'Onde foi o lugar mais ousado que você já se envolveu com alguém?',
      'O que é um deal breaker na cama?',
      'O que deixa qualquer um no clima na hora?',
      'Qual a mentira mais contada sobre a vida sexual?',
      'O que você acha superestimado no sexo?',
      'Qual o maior mito sobre transar?',
      'O que é atraente e ninguém admite?',
      'Qual a coisa mais constrangedora que pode rolar na cama?',
      'O que é sexy numa mensagem?',
      'Qual tipo de beijo é o melhor?',
      'O que é um turn off imediato?',
      'Qual a fantasia mais clichê que existe?',
      'Qual o pior lugar pra receber uma cantada?',
      'O que toda pessoa exagera quando conta sobre sexo?',
      'Qual a melhor forma de dar em cima de alguém?',
      'Qual gesto é mais provocante que parece?',
      'O que é o maior tesão numa pessoa?',
    ],
  },
];

// Categorias marcadas por padrão: só as "gerais", que qualquer grupo responde de boa.
// Fora do padrão: Famosos, Filmes, Música, Hot Takes, Relacionamentos e NSFW
// (essas o usuário liga se quiser).
export const DEFAULT_QUESTION_CATEGORY_IDS = ['galera', 'comida', 'lugares', 'vida-social'];

// Sorteia uma categoria (dentre as selecionadas, incluindo as personalizadas),
// uma pergunta "real" e uma pergunta "fake" (diferente, mesma categoria) para o impostor.
export const drawQuestionRound = (
  selectedIds?: string[],
  customCategories?: QuestionCategory[]
): { category: string; question: string; fakeQuestion: string } => {
  const all = [...QUESTION_CATEGORIES, ...(customCategories || [])];
  const pool = selectedIds && selectedIds.length > 0
    ? all.filter(c => selectedIds.includes(c.id))
    : all;
  const categories = pool.length > 0 ? pool : QUESTION_CATEGORIES;
  const category = categories[Math.floor(Math.random() * categories.length)];
  const questions = category.questions;
  const realIndex = Math.floor(Math.random() * questions.length);
  const real = questions[realIndex];

  // A pergunta do impostor precisa pedir o MESMO tipo de resposta que a real,
  // senão fica óbvia. Uma pergunta de "Quem..." (resposta = pessoa) nunca deve
  // parear com uma de "Qual/O que..." (resposta = coisa). Isso importa em
  // categorias mistas como a NSFW.
  const isWho = (q: string) => q.trim().toLowerCase().startsWith('quem');
  let candidates = questions.filter((q, i) => i !== realIndex && isWho(q) === isWho(real));
  if (candidates.length === 0) {
    candidates = questions.filter((_, i) => i !== realIndex);
  }
  const fake = candidates.length > 0
    ? candidates[Math.floor(Math.random() * candidates.length)]
    : real;

  return {
    category: category.name,
    question: real,
    fakeQuestion: fake,
  };
};
